import type { LearningContent } from "./types";

/**
 * A handful of clearly-marked SAMPLE records — not a real content library.
 * They exist only to prove the content model, cards, and filter UI work
 * end to end. Every place that renders these must show a "Sample" badge
 * (see `LearningCard`'s `isSample` prop); do not treat this file as a
 * pattern for bulk-generating content.
 *
 * Deliberately none are in a Qur'an/Arabic category — those stay empty
 * until real, human-reviewed content exists (see RELIGIOUS_REVIEW_REQUIRED
 * _CATEGORIES in ./types.ts).
 */
export const SAMPLE_CONTENT: LearningContent[] = [
  {
    id: "sample-1",
    slug: "counting-to-ten-practice-sheet",
    title: "Counting to Ten — Practice Sheet",
    description: "A printable sheet for practicing counting objects from one to ten.",
    category: "mathematics",
    ageRange: { minYears: 3, maxYears: 5 },
    learningObjective: "Count a small group of objects accurately.",
    difficulty: "beginner",
    contentType: "worksheet",
    tags: ["counting", "numbers"],
    author: { name: "Little Learners Learning", role: "platform" },
    publicationStatus: "published",
    religiousReview: "not-applicable",
    featured: true,
    createdAt: "2026-01-15",
    updatedAt: "2026-01-15",
  },
  {
    id: "sample-2",
    slug: "letter-sounds-a-to-e",
    title: "Letter Sounds: A to E",
    description: "An introductory lesson on the sounds made by the first five letters of the alphabet.",
    category: "english-early-literacy",
    ageRange: { minYears: 3, maxYears: 5 },
    learningObjective: "Match each letter A–E to its sound.",
    difficulty: "beginner",
    contentType: "lesson",
    tags: ["phonics", "alphabet"],
    author: { name: "Little Learners Learning", role: "platform" },
    publicationStatus: "published",
    religiousReview: "not-applicable",
    featured: true,
    createdAt: "2026-01-15",
    updatedAt: "2026-01-15",
  },
  {
    id: "sample-3",
    slug: "getting-dressed-independently",
    title: "Getting Dressed Independently",
    description: "A step-by-step activity that walks through getting dressed without help.",
    category: "life-skills",
    ageRange: { minYears: 2, maxYears: 4 },
    learningObjective: "Follow a short sequence of steps to get dressed.",
    difficulty: "beginner",
    contentType: "activity",
    tags: ["independence", "routines"],
    author: { name: "Little Learners Learning", role: "platform" },
    publicationStatus: "published",
    religiousReview: "not-applicable",
    featured: false,
    createdAt: "2026-01-20",
    updatedAt: "2026-01-20",
  },
  {
    id: "sample-4",
    slug: "shape-matching-puzzle",
    title: "Shape Matching Puzzle",
    description: "A simple matching puzzle pairing everyday objects with their basic shape.",
    category: "puzzles",
    ageRange: { minYears: 3, maxYears: 5 },
    learningObjective: "Match everyday objects to their basic shape.",
    difficulty: "beginner",
    contentType: "puzzle",
    tags: ["shapes", "matching"],
    author: { name: "Little Learners Learning", role: "platform" },
    publicationStatus: "published",
    religiousReview: "not-applicable",
    featured: false,
    createdAt: "2026-01-22",
    updatedAt: "2026-01-22",
  },
  {
    id: "sample-5",
    slug: "the-four-seasons",
    title: "The Four Seasons",
    description: "A simple look at spring, summer, autumn, and winter, and one real change to notice in each.",
    category: "world-around-us",
    ageRange: { minYears: 3, maxYears: 6 },
    learningObjective: "Name the four seasons and describe one change in each.",
    difficulty: "beginner",
    contentType: "lesson",
    tags: ["seasons", "weather"],
    author: { name: "Little Learners Learning", role: "platform" },
    publicationStatus: "published",
    religiousReview: "not-applicable",
    featured: false,
    createdAt: "2026-03-01",
    updatedAt: "2026-03-01",
  },
  {
    id: "sample-6",
    slug: "what-floats-what-sinks",
    title: "What Floats? What Sinks?",
    description: "An introduction to the idea that some objects float in water and others sink.",
    category: "science-discovery",
    ageRange: { minYears: 4, maxYears: 7 },
    learningObjective: "Predict and describe whether an object floats or sinks.",
    difficulty: "beginner",
    contentType: "lesson",
    tags: ["science", "cause-and-effect"],
    author: { name: "Little Learners Learning", role: "platform" },
    publicationStatus: "published",
    religiousReview: "not-applicable",
    featured: false,
    createdAt: "2026-03-02",
    updatedAt: "2026-03-02",
  },
  {
    id: "sample-7",
    slug: "naming-our-feelings",
    title: "Naming Our Feelings",
    description: "An introduction to naming common feelings like happy, sad, angry, and worried.",
    category: "social-emotional-learning",
    ageRange: { minYears: 2, maxYears: 6 },
    learningObjective: "Name a feeling using a simple feelings word.",
    difficulty: "beginner",
    contentType: "lesson",
    tags: ["emotions", "feelings"],
    author: { name: "Little Learners Learning", role: "platform" },
    publicationStatus: "published",
    religiousReview: "not-applicable",
    featured: false,
    createdAt: "2026-03-03",
    updatedAt: "2026-03-03",
  },
  {
    id: "sample-8",
    slug: "sorting-by-color-and-size",
    title: "Sorting by Color and Size",
    description: "A hands-on sorting activity using everyday objects grouped by color or size.",
    category: "educational-activities",
    ageRange: { minYears: 3, maxYears: 6 },
    learningObjective: "Sort a group of objects by one shared property.",
    difficulty: "beginner",
    contentType: "activity",
    tags: ["sorting", "hands-on"],
    author: { name: "Little Learners Learning", role: "platform" },
    publicationStatus: "published",
    religiousReview: "not-applicable",
    featured: false,
    createdAt: "2026-03-04",
    updatedAt: "2026-03-04",
  },
  {
    id: "sample-9",
    slug: "why-mazes-are-good-practice",
    title: "Why Mazes Are Good Practice",
    description: "A short explanation of what tracing a maze helps a young child practice: following a path with their eyes and hand together.",
    category: "mazes",
    ageRange: { minYears: 4, maxYears: 7 },
    learningObjective: "Understand what a maze is practicing before trying one.",
    difficulty: "beginner",
    contentType: "lesson",
    tags: ["maze", "fine-motor"],
    author: { name: "Little Learners Learning", role: "platform" },
    publicationStatus: "published",
    religiousReview: "not-applicable",
    featured: false,
    createdAt: "2026-03-05",
    updatedAt: "2026-03-05",
  },
  {
    id: "sample-10",
    slug: "colors-all-around-us",
    title: "Colors All Around Us",
    description: "A simple activity for naming colors seen in everyday objects around the home.",
    category: "coloring",
    ageRange: { minYears: 2, maxYears: 5 },
    learningObjective: "Name a color and find a real object that matches it.",
    difficulty: "beginner",
    contentType: "lesson",
    tags: ["color-recognition", "colors"],
    author: { name: "Little Learners Learning", role: "platform" },
    publicationStatus: "published",
    religiousReview: "not-applicable",
    featured: false,
    createdAt: "2026-03-06",
    updatedAt: "2026-03-06",
  },
  {
    id: "sample-11",
    slug: "five-learning-games-no-screen-needed",
    title: "Five Learning Games With No Screen Needed",
    description: "A short list of simple verbal and physical games that build early learning skills without any equipment.",
    category: "learning-games",
    ageRange: { minYears: 3, maxYears: 7 },
    learningObjective: "Practice a learning skill through play, with no screen or materials needed.",
    difficulty: "beginner",
    contentType: "activity",
    tags: ["no-screen", "verbal-games"],
    author: { name: "Little Learners Learning", role: "platform" },
    publicationStatus: "published",
    religiousReview: "not-applicable",
    featured: false,
    createdAt: "2026-03-07",
    updatedAt: "2026-03-07",
  },
];
