import type { Resource } from "./types";

/**
 * A handful of clearly-marked SAMPLE resources — not a real library. They
 * exist to prove the model, cards, filters, and detail pages work end to
 * end. None has a real `downloadFile`, so no UI should ever show a working
 * download action for these (see `canDownload` in ./types.ts).
 *
 * One entry (`arabic-letters-tracing-pack`) is deliberately unverified
 * religious-adjacent content, included specifically to prove
 * `isResourcePublished` hides it — see sample-resources.test.ts.
 */
export const SAMPLE_RESOURCES: Resource[] = [
  {
    id: "resource-1",
    slug: "counting-animals-worksheet",
    title: "Counting Animals Worksheet",
    description: "A printable worksheet practicing counting groups of farm animals up to ten.",
    resourceType: "worksheet",
    activitySubtype: "counting",
    category: "mathematics",
    ageRange: { minYears: 3, maxYears: 5 },
    difficulty: "beginner",
    learningObjective: "Count a group of up to ten objects.",
    skillsDeveloped: ["One-to-one counting", "Number recognition 1–10"],
    instructions: [
      "Look at each group of animals.",
      "Count how many animals are in the group.",
      "Write the number in the box next to the group.",
    ],
    tags: ["counting", "numbers"],
    author: { name: "Little Learners Learning", role: "platform" },
    accessTier: "free",
    featured: true,
    publicationStatus: "published",
    religiousReview: "not-applicable",
    createdAt: "2026-02-01",
    updatedAt: "2026-02-01",
  },
  {
    id: "resource-2",
    slug: "first-shapes-ebook",
    title: "First Shapes",
    subtitle: "An early introduction to circles, squares, and triangles",
    description: "A short illustrated ebook introducing circles, squares, and triangles.",
    resourceType: "ebook",
    category: "mathematics",
    ageRange: { minYears: 2, maxYears: 4 },
    difficulty: "beginner",
    learningObjective: "Name basic shapes on sight.",
    learningObjectives: ["Name a circle, square, and triangle on sight", "Spot each shape in everyday objects"],
    skillsDeveloped: ["Shape recognition", "Visual discrimination"],
    pageCount: 14,
    tags: ["shapes"],
    author: { name: "Little Learners Learning", role: "platform" },
    accessTier: "premium",
    featured: true,
    publicationStatus: "published",
    religiousReview: "not-applicable",
    createdAt: "2026-02-03",
    updatedAt: "2026-02-03",
  },
  {
    id: "resource-3",
    slug: "classroom-circle-time-ideas",
    title: "Classroom Circle Time Ideas",
    description: "A short list of circle-time routines for early-years classrooms.",
    resourceType: "teacher-resource",
    subject: "Classroom Management",
    ageRange: { minYears: 3, maxYears: 6 },
    difficulty: "beginner",
    learningObjective: "Give teachers a repeatable circle-time structure.",
    tags: ["classroom", "routines"],
    author: { name: "Little Learners Learning", role: "platform" },
    accessTier: "free",
    featured: false,
    publicationStatus: "published",
    religiousReview: "not-applicable",
    createdAt: "2026-02-05",
    updatedAt: "2026-02-05",
  },
  {
    id: "resource-4",
    slug: "screen-time-conversation-starters",
    title: "Screen-Time Conversation Starters",
    description: "A short set of questions parents can use to talk with their child about screen time.",
    resourceType: "parent-resource",
    subject: "Family Routines",
    ageRange: { minYears: 3, maxYears: 7 },
    difficulty: "beginner",
    learningObjective: "Help parents open a conversation about screen time.",
    tags: ["parenting"],
    author: { name: "Little Learners Learning", role: "platform" },
    accessTier: "free",
    featured: false,
    publicationStatus: "published",
    religiousReview: "not-applicable",
    createdAt: "2026-02-06",
    updatedAt: "2026-02-06",
  },
  {
    id: "resource-5",
    slug: "arabic-letters-tracing-pack",
    title: "Arabic Letters Tracing Pack",
    description: "A tracing worksheet pack for the first few letters of the Arabic alphabet.",
    resourceType: "worksheet",
    activitySubtype: "tracing",
    category: "arabic-letters",
    ageRange: { minYears: 3, maxYears: 5 },
    difficulty: "beginner",
    learningObjective: "Trace and recognize the first Arabic letters.",
    tags: ["arabic", "tracing"],
    author: { name: "Little Learners Learning", role: "platform" },
    accessTier: "free",
    featured: false,
    publicationStatus: "published",
    // Not yet reviewed — isResourcePublished() must hide this from every
    // public listing until a qualified person marks it "verified".
    religiousReview: "pending-review",
    createdAt: "2026-02-08",
    updatedAt: "2026-02-08",
  },
  {
    id: "resource-6",
    slug: "tracing-straight-lines-activity",
    title: "Tracing Straight Lines",
    description: "A hands-on tracing activity building the pencil control needed before letter writing.",
    resourceType: "activity",
    activitySubtype: "tracing",
    category: "early-writing",
    ageRange: { minYears: 3, maxYears: 5 },
    difficulty: "beginner",
    learningObjective: "Trace a straight line without lifting the pencil.",
    skillsDeveloped: ["Pencil grip", "Hand-eye coordination"],
    materialsRequired: ["A pencil or crayon", "A printed tracing sheet"],
    instructions: [
      "Sit at a table with the tracing sheet in front of your child.",
      "Show them how to start at the dot and trace to the arrow.",
      "Let them trace each line at their own pace — it's okay to go slowly.",
      "Celebrate finishing, even if the lines aren't perfectly straight.",
    ],
    tags: ["fine-motor", "pre-writing"],
    author: { name: "Little Learners Learning", role: "platform" },
    accessTier: "free",
    featured: false,
    publicationStatus: "published",
    religiousReview: "not-applicable",
    createdAt: "2026-02-10",
    updatedAt: "2026-02-10",
  },
  {
    id: "resource-7",
    slug: "my-first-letters-booklet",
    title: "My First Letters",
    subtitle: "A gentle first look at the alphabet",
    description: "A short, free booklet introducing the shapes and sounds of the first few letters.",
    resourceType: "ebook",
    category: "english-early-literacy",
    ageRange: { minYears: 2, maxYears: 4 },
    difficulty: "beginner",
    learningObjective: "Recognize the first few letters of the alphabet.",
    learningObjectives: ["Recognize A, B, and C by sight", "Connect each letter to its sound"],
    skillsDeveloped: ["Letter recognition", "Phonemic awareness"],
    pageCount: 10,
    tags: ["alphabet", "phonics"],
    author: { name: "Little Learners Learning", role: "platform" },
    accessTier: "free",
    featured: false,
    publicationStatus: "published",
    religiousReview: "not-applicable",
    createdAt: "2026-02-12",
    updatedAt: "2026-02-12",
  },
  {
    id: "resource-8",
    slug: "daily-weather-watch",
    title: "Daily Weather Watch",
    description: "A short daily routine for noticing and naming the day's weather.",
    resourceType: "activity",
    activitySubtype: "general",
    category: "world-around-us",
    ageRange: { minYears: 3, maxYears: 5 },
    difficulty: "beginner",
    learningObjective: "Observe and describe the day's weather using simple words.",
    skillsDeveloped: ["Observation", "Weather and seasons vocabulary"],
    materialsRequired: ["A window, or a chance to step outside"],
    instructions: [
      "At around the same time each day, look outside together.",
      "Ask: is it sunny, cloudy, rainy, or windy today?",
      "Say the word out loud together, and talk about why you're dressed the way you are because of it.",
      "After a week, look back and talk about which type of day happened the most.",
    ],
    tags: ["weather", "observation", "seasons"],
    author: { name: "Little Learners Learning", role: "platform" },
    accessTier: "free",
    featured: false,
    publicationStatus: "published",
    religiousReview: "not-applicable",
    createdAt: "2026-03-01",
    updatedAt: "2026-03-01",
  },
  {
    id: "resource-9",
    slug: "sink-or-float-experiment",
    title: "Sink or Float Experiment",
    description: "A hands-on experiment testing which household objects float and which sink.",
    resourceType: "activity",
    activitySubtype: "general",
    category: "science-discovery",
    ageRange: { minYears: 4, maxYears: 7 },
    difficulty: "beginner",
    learningObjective: "Test a prediction using a simple, safe experiment.",
    skillsDeveloped: ["Prediction", "Observation", "Simple cause-and-effect thinking"],
    materialsRequired: [
      "A clear bowl or tub of water",
      "5–6 safe household objects (e.g. a spoon, a cork, a coin, a plastic toy, a stone, a sponge)",
    ],
    instructions: [
      "Lay out the objects and ask your child to guess which will float and which will sink.",
      "Test one object at a time, saying what happens out loud.",
      "Sort the objects into two groups: 'floated' and 'sank'.",
      "Talk about what the floating objects had in common, and what the sinking ones had in common.",
    ],
    tags: ["science", "experiment", "cause-and-effect"],
    author: { name: "Little Learners Learning", role: "platform" },
    accessTier: "free",
    featured: false,
    publicationStatus: "published",
    religiousReview: "not-applicable",
    createdAt: "2026-03-02",
    updatedAt: "2026-03-02",
  },
  {
    id: "resource-10",
    slug: "feelings-check-in",
    title: "Feelings Check-In",
    description: "A simple daily routine for checking in on how a child is feeling and why.",
    resourceType: "activity",
    activitySubtype: "general",
    category: "social-emotional-learning",
    ageRange: { minYears: 2, maxYears: 6 },
    difficulty: "beginner",
    learningObjective: "Identify and share a current feeling using a simple word.",
    skillsDeveloped: ["Emotional vocabulary", "Communication"],
    instructions: [
      "Ask, \"How are you feeling right now?\"",
      "If they're not sure, offer a few words to choose from: happy, sad, angry, worried, excited.",
      "Ask what made them feel that way, and just listen — there's no need to fix or change the feeling.",
      "Thank them for sharing, so checking in stays a welcome, everyday habit.",
    ],
    tags: ["emotions", "feelings", "communication"],
    author: { name: "Little Learners Learning", role: "platform" },
    accessTier: "free",
    featured: false,
    publicationStatus: "published",
    religiousReview: "not-applicable",
    createdAt: "2026-03-03",
    updatedAt: "2026-03-03",
  },
  {
    id: "resource-11",
    slug: "kitchen-sorting-challenge",
    title: "Kitchen Sorting Challenge",
    description: "A hands-on sorting activity using safe items from around the home.",
    resourceType: "activity",
    activitySubtype: "sorting",
    category: "educational-activities",
    ageRange: { minYears: 3, maxYears: 6 },
    difficulty: "beginner",
    learningObjective: "Sort a group of objects by color, size, or shape.",
    skillsDeveloped: ["Classification", "Following instructions", "Fine motor handling"],
    materialsRequired: ["8–10 safe household items of different colors or sizes (buttons, blocks, spoons, socks)"],
    instructions: [
      "Lay all the items out together in one pile.",
      "Pick one rule together, e.g. \"let's sort by color\".",
      "Move the items into small groups that match the rule.",
      "Try again with a new rule, like sorting by size instead.",
    ],
    tags: ["sorting", "hands-on"],
    author: { name: "Little Learners Learning", role: "platform" },
    accessTier: "free",
    featured: false,
    publicationStatus: "published",
    religiousReview: "not-applicable",
    createdAt: "2026-03-04",
    updatedAt: "2026-03-04",
  },
  {
    id: "resource-12",
    slug: "first-maze-find-the-way-home",
    title: "First Maze — Find the Way Home",
    description: "A simple, single-path maze for a child's very first maze-tracing experience.",
    resourceType: "maze",
    category: "mazes",
    ageRange: { minYears: 4, maxYears: 6 },
    difficulty: "beginner",
    learningObjective: "Trace a single path from start to finish without crossing a line.",
    skillsDeveloped: ["Visual tracking", "Fine-motor control", "Focus"],
    materialsRequired: ["A pencil or crayon", "A printed maze sheet"],
    instructions: [
      "Find the start and finish points on the maze first, before picking up the pencil.",
      "Trace the path slowly, staying inside the lines.",
      "It's fine to pause partway and continue later — there's no time limit.",
      "Celebrate reaching the finish, however long the path took.",
    ],
    tags: ["maze", "fine-motor", "focus"],
    author: { name: "Little Learners Learning", role: "platform" },
    accessTier: "free",
    featured: false,
    publicationStatus: "published",
    religiousReview: "not-applicable",
    createdAt: "2026-03-05",
    updatedAt: "2026-03-05",
  },
  {
    id: "resource-13",
    slug: "my-first-shapes-coloring-page",
    title: "My First Shapes Coloring Page",
    description: "A simple coloring page featuring basic shapes for early color and shape recognition.",
    resourceType: "coloring",
    category: "coloring",
    ageRange: { minYears: 2, maxYears: 5 },
    difficulty: "beginner",
    learningObjective: "Color within a simple shape using a chosen color.",
    skillsDeveloped: ["Fine-motor control", "Color recognition", "Shape recognition"],
    materialsRequired: ["Crayons or colored pencils", "A printed coloring page"],
    instructions: [
      "Let your child pick which shape to color first.",
      "Name the shape and the color they've chosen together.",
      "Let them color at their own pace — going outside the lines is completely fine.",
      "Ask them to name the shape and color again once they're done.",
    ],
    tags: ["coloring", "color-recognition", "shapes"],
    author: { name: "Little Learners Learning", role: "platform" },
    accessTier: "free",
    featured: false,
    publicationStatus: "published",
    religiousReview: "not-applicable",
    createdAt: "2026-03-06",
    updatedAt: "2026-03-06",
  },
];
